"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
import sys

import setuptools.dist


# uv-managed Python (python-build-standalone) ships Tcl/Tk 9.0 inside the
# interpreter prefix on both arm64 and x86_64 (we pin Python 3.13), but
# hardcodes its own build path inside libtcl. py2app's tkinter recipe calls
# ``_tkinter.create()`` during the build, which fails unless TCL_LIBRARY /
# TK_LIBRARY point at the real locations. Set them automatically when not
# already provided.
if "TCL_LIBRARY" not in os.environ or "TK_LIBRARY" not in os.environ:
    # ``sys.base_prefix`` points at the underlying Python install rather
    # than the venv, where the Tcl/Tk runtime files actually live.
    _tcl_dir = os.path.join(sys.base_prefix, "lib", "tcl9.0")
    _tk_dir = os.path.join(sys.base_prefix, "lib", "tk9.0")
    if os.path.isdir(_tcl_dir) and os.path.isdir(_tk_dir):
        os.environ.setdefault("TCL_LIBRARY", _tcl_dir)
        os.environ.setdefault("TK_LIBRARY", _tk_dir)

# py2app rejects ``install_requires``, but setuptools >= 77 reads
# ``[project] dependencies`` from pyproject.toml during ``parse_config_files``
# and assigns them onto the Distribution. Strip them back out afterwards so
# py2app's command class is happy. Runtime deps are still installed by
# ``uv sync`` into the .venv that py2app bundles into the .app.
_orig_parse_config_files = setuptools.dist.Distribution.parse_config_files

def _patched_parse_config_files(self, *args, **kwargs):
    result = _orig_parse_config_files(self, *args, **kwargs)
    self.install_requires = []
    return result

setuptools.dist.Distribution.parse_config_files = _patched_parse_config_files

# uv-managed Python (python-build-standalone) statically links zlib into the
# interpreter, so ``zlib.__file__`` does not exist. py2app unconditionally
# tries to copy ``zlib.__file__`` into the bundle, which fails. Since zlib is
# already inside the bundled interpreter binary, we can safely skip the copy.
import zlib
if "py2app" in sys.argv and not hasattr(zlib, "__file__"):
    _BUILTIN_SENTINEL = "<py2app:builtin-zlib>"
    zlib.__file__ = _BUILTIN_SENTINEL

    import py2app.build_app as _build_app
    _orig_copy_file = _build_app.py2app.copy_file

    def _patched_copy_file(self, src, *args, **kwargs):
        if src == _BUILTIN_SENTINEL:
            return (src, 0)
        return _orig_copy_file(self, src, *args, **kwargs)

    _build_app.py2app.copy_file = _patched_copy_file

from setuptools import setup

APP = ['Synology.py']
APP_NAME = "Open Source Synology Cloud Sync Decryption Tool"
DATA_FILES = ["app.gif"]
OPTIONS = {'packages' : ['syndecrypt', 'lz4', 'PIL', 'Cryptodome'],
            'argv_emulation': True,
            'emulate_shell_environment': True,
            'iconfile': 'app.icns',
            'plist': {
                'CFBundleName': APP_NAME,
                'CFBundleDisplayName': APP_NAME,
                'CFBundleGetInfoString': "Open Source Synology Cloud Sync Decryption Tool",
                'CFBundleIdentifier': "com.anojht.osx.synologycloudsyncdecryptiontool",
                'CFBundleVersion': "11.0.0",
                'CFBundleShortVersionString': "11.0.0",
                'NSHumanReadableCopyright': "Copyright 2026, Anojh Thayaparan, All Rights Reserved"
                }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)


# ---------------------------------------------------------------------------
# Post-build: bundle Tcl/Tk into the .app
# ---------------------------------------------------------------------------
# python-build-standalone (used by uv) ships Tcl/Tk 9.0 as plain .dylibs plus
# script directories under ``<base>/lib/{tcl9.0,tk9.0}``. py2app's tkinter
# recipe is wired for the python.org installer's Tcl.framework/Tk.framework
# layout, so the .app it produces is missing the libraries entirely.
#
# After py2app finishes, copy the .dylibs next to ``_tkinter.so`` (which has
# ``LC_RPATH = @loader_path/../..``) and copy the script directories under
# ``Contents/Resources/lib/`` so the runtime hook in ``syndecrypt/gui.py``
# can point ``TCL_LIBRARY`` / ``TK_LIBRARY`` at them.
if "py2app" in sys.argv:
    import shutil

    _bundle = os.path.join(
        "dist",
        APP_NAME + ".app",
        "Contents",
        "Resources",
    )
    if os.path.isdir(_bundle):
        _src_lib = os.path.join(sys.base_prefix, "lib")
        # ``_tkinter.so`` lives at Resources/lib/python3.13/lib-dynload/ and
        # has LC_RPATH = @loader_path/../.. which resolves to Resources/lib/.
        _dylib_dst = os.path.join(_bundle, "lib")
        os.makedirs(_dylib_dst, exist_ok=True)
        # Tk 9 ships its dylibs as ``libtcl9.0.dylib`` and
        # ``libtcl9tk9.0.dylib`` (Tk 9 split things differently from 8.6).
        for _name in ("libtcl9.0.dylib", "libtcl9tk9.0.dylib"):
            _src = os.path.join(_src_lib, _name)
            if os.path.isfile(_src):
                shutil.copy2(_src, os.path.join(_dylib_dst, _name))

        _scripts_dst = os.path.join(_bundle, "lib")
        for _name in ("tcl9.0", "tk9.0"):
            _src = os.path.join(_src_lib, _name)
            _dst = os.path.join(_scripts_dst, _name)
            if os.path.isdir(_src) and not os.path.isdir(_dst):
                shutil.copytree(_src, _dst, symlinks=True)

        # Tk's bundled ``console.tcl`` builds an internal Tcl console window
        # during ``TkpInit`` and configures it with a main menubar. On macOS
        # 26 (Tahoe) AppKit aborts when ``NSMenuItem`` is created with a nil
        # title — which is what Tk's menubar code passes — so the app
        # crashes the moment ``tkinter.Tk()`` is constructed in any GUI-
        # launched .app (no controlling TTY → console window is shown →
        # menubar setup runs → SIGABRT). The bug is present in Tk 9.0, so
        # stub the script in the bundled tk9.0 directory.
        _console_tcl = os.path.join(_scripts_dst, "tk9.0", "console.tcl")
        if os.path.isfile(_console_tcl):
            with open(_console_tcl, "w") as _f:
                _f.write(
                    "# Replaced by setup.py post-build: Tk's internal console\n"
                    "# window crashes the app on macOS 26 because of a nil-title\n"
                    "# NSMenuItem in the menubar setup. We do not need the\n"
                    "# console, so stub everything out.\n"
                    "namespace eval ::tk {}\n"
                    "proc ::tk::ConsoleInit {} {}\n"
                    "proc ::tk::ConsoleExit {} {}\n"
                    "proc ::tk::ConsoleAbout {} {}\n"
                    "proc ::tk::ConsoleHistory {args} {}\n"
                    "proc ::tk::ConsoleSource {} {}\n"
                    "proc ::tk::ConsoleInvoke {args} {}\n"
                    "proc ::tk::ConsolePrompt {args} {}\n"
                    "proc ::tk::ConsoleOutput {args} {}\n"
                )

        print("post-build: bundled Tcl/Tk 9.0 libraries and script directories")
