"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import glob
import os
import re
import sys

import setuptools.dist


def _find_tcl_tk_script_dirs(lib_dir):
    """Return ``(tcl_dir, tk_dir)`` for the highest version of Tcl/Tk
    found under ``lib_dir``. python-build-standalone ships Tcl/Tk 8.6 in
    arm64 builds and Tcl/Tk 9.0 in x86_64 builds, so we cannot hardcode
    a version. Returns ``(None, None)`` if nothing is found."""
    def _highest(prefix):
        candidates = []
        for path in glob.glob(os.path.join(lib_dir, prefix + "[0-9]*.[0-9]*")):
            name = os.path.basename(path)
            m = re.fullmatch(re.escape(prefix) + r"(\d+)\.(\d+)", name)
            if m and os.path.isdir(path):
                candidates.append(((int(m.group(1)), int(m.group(2))), path))
        candidates.sort()
        return candidates[-1][1] if candidates else None
    return _highest("tcl"), _highest("tk")


# uv-managed Python (python-build-standalone) ships Tcl/Tk inside the
# interpreter prefix but hardcodes its own build path inside libtcl. py2app's
# tkinter recipe calls ``_tkinter.create()`` during the build, which fails
# unless TCL_LIBRARY/TK_LIBRARY point at the real locations. Set them
# automatically when not already provided.
if "TCL_LIBRARY" not in os.environ or "TK_LIBRARY" not in os.environ:
    # ``sys.base_prefix`` points at the underlying Python install rather than
    # the venv, where the Tcl/Tk runtime files actually live.
    _tcl_dir, _tk_dir = _find_tcl_tk_script_dirs(os.path.join(sys.base_prefix, "lib"))
    if _tcl_dir and _tk_dir:
        os.environ.setdefault("TCL_LIBRARY", _tcl_dir)
        os.environ.setdefault("TK_LIBRARY", _tk_dir)

# py2app rejects ``install_requires``, but setuptools >= 77 reads
# ``[project] dependencies`` from pyproject.toml during ``parse_config_files``
# and assigns them onto the Distribution. Strip them back out afterwards so
# py2app's command class is happy. Runtime deps are still installed by
# ``uv sync`` into the .venv that py2app bundles into the .app.
_orig_parse_config_files = setuptools.dist.Distribution.parse_config_files

def _patched_parse_config_files(self, *args, **kwargs):
    result = _orig_parse_config_files(self, *args, **kwargs)
    self.install_requires = []
    return result

setuptools.dist.Distribution.parse_config_files = _patched_parse_config_files

# uv-managed Python (python-build-standalone) statically links zlib into the
# interpreter, so ``zlib.__file__`` does not exist. py2app unconditionally
# tries to copy ``zlib.__file__`` into the bundle, which fails. Since zlib is
# already inside the bundled interpreter binary, we can safely skip the copy.
import zlib
if not hasattr(zlib, "__file__"):
    _BUILTIN_SENTINEL = "<py2app:builtin-zlib>"
    zlib.__file__ = _BUILTIN_SENTINEL

    import py2app.build_app as _build_app
    _orig_copy_file = _build_app.py2app.copy_file

    def _patched_copy_file(self, src, *args, **kwargs):
        if src == _BUILTIN_SENTINEL:
            return (src, 0)
        return _orig_copy_file(self, src, *args, **kwargs)

    _build_app.py2app.copy_file = _patched_copy_file

from setuptools import setup

APP = ['Synology.py']
APP_NAME = "Open Source Synology Cloud Sync Decryption Tool"
DATA_FILES = ["app.gif"]
OPTIONS = {'packages' : ['syndecrypt', 'lz4', 'PIL', 'Cryptodome'],
            'argv_emulation': True,
            'emulate_shell_environment': True,
            'iconfile': 'app.icns',
            'plist': {
                'CFBundleName': APP_NAME,
                'CFBundleDisplayName': APP_NAME,
                'CFBundleGetInfoString': "Open Source Synology Cloud Sync Decryption Tool",
                'CFBundleIdentifier': "com.anojht.osx.synologycloudsyncdecryptiontool",
                'CFBundleVersion': "10.0.0",
                'CFBundleShortVersionString': "10.0.0",
                'NSHumanReadableCopyright': "Copyright 2026, Anojh Thayaparan, All Rights Reserved"
                }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
)


# ---------------------------------------------------------------------------
# Post-build: bundle Tcl/Tk into the .app
# ---------------------------------------------------------------------------
# python-build-standalone (used by uv) ships Tcl/Tk as plain .dylibs plus
# script directories under ``<base>/lib/{tcl8.6,tk8.6}``. py2app's tkinter
# recipe is wired for the python.org installer's Tcl.framework/Tk.framework
# layout, so the .app it produces is missing the libraries entirely.
#
# After py2app finishes, copy the .dylibs next to ``_tkinter.so`` (which has
# ``LC_RPATH = @loader_path/../..``) and copy the script directories under
# ``Contents/Resources/lib/`` so the runtime hook in ``Synology.py`` can point
# ``TCL_LIBRARY`` / ``TK_LIBRARY`` at them.
if "py2app" in sys.argv:
    import shutil

    _bundle = os.path.join(
        "dist",
        APP_NAME + ".app",
        "Contents",
        "Resources",
    )
    if os.path.isdir(_bundle):
        _src_lib = os.path.join(sys.base_prefix, "lib")
        # ``_tkinter.so`` lives at Resources/lib/python3.12/lib-dynload/ and
        # has LC_RPATH = @loader_path/../.. which resolves to Resources/lib/.
        _dylib_dst = os.path.join(_bundle, "lib")
        os.makedirs(_dylib_dst, exist_ok=True)
        # Copy every Tcl/Tk dylib in the base prefix. arm64 PBS Python ships
        # ``libtcl8.6.dylib`` + ``libtk8.6.dylib``; x86_64 PBS Python ships
        # ``libtcl9.0.dylib`` + ``libtcl9tk9.0.dylib`` (Tk 9 split things
        # differently). Globbing keeps us version-agnostic.
        _dylib_globs = ("libtcl*.dylib", "libtk*.dylib", "libtcl*tk*.dylib")
        _copied_dylibs = []
        for _pattern in _dylib_globs:
            for _src in glob.glob(os.path.join(_src_lib, _pattern)):
                _name = os.path.basename(_src)
                shutil.copy2(_src, os.path.join(_dylib_dst, _name))
                _copied_dylibs.append(_name)

        _scripts_dst = os.path.join(_bundle, "lib")
        # Copy every ``tclX[.Y]`` and ``tkX[.Y]`` script directory we find.
        _copied_scripts = []
        for _pattern in ("tcl[0-9]*", "tk[0-9]*"):
            for _src in glob.glob(os.path.join(_src_lib, _pattern)):
                _name = os.path.basename(_src)
                _dst = os.path.join(_scripts_dst, _name)
                if os.path.isdir(_src) and not os.path.isdir(_dst):
                    shutil.copytree(_src, _dst, symlinks=True)
                    _copied_scripts.append(_name)

        # Tk's bundled ``console.tcl`` builds an internal Tcl console window
        # during ``TkpInit`` and configures it with a main menubar. On macOS
        # 26 (Tahoe) AppKit aborts when ``NSMenuItem`` is created with a nil
        # title — which is what Tk's menubar code passes — so the app
        # crashes the moment ``tkinter.Tk()`` is constructed in any GUI-
        # launched .app (no controlling TTY → console window is shown →
        # menubar setup runs → SIGABRT). The bug is present in both Tk 8.6
        # (arm64 PBS Python) and Tk 9.0 (x86_64 PBS Python), so stub the
        # script in *every* tk*.* directory we bundled.
        _stub_tcl = (
            "# Replaced by setup.py post-build: Tk's internal console\n"
            "# window crashes the app on macOS 26 because of a nil-title\n"
            "# NSMenuItem in the menubar setup. We do not need the\n"
            "# console, so stub everything out.\n"
            "namespace eval ::tk {}\n"
            "proc ::tk::ConsoleInit {} {}\n"
            "proc ::tk::ConsoleExit {} {}\n"
            "proc ::tk::ConsoleAbout {} {}\n"
            "proc ::tk::ConsoleHistory {args} {}\n"
            "proc ::tk::ConsoleSource {} {}\n"
            "proc ::tk::ConsoleInvoke {args} {}\n"
            "proc ::tk::ConsolePrompt {args} {}\n"
            "proc ::tk::ConsoleOutput {args} {}\n"
        )
        for _tk_dir in glob.glob(os.path.join(_scripts_dst, "tk[0-9]*.[0-9]*")):
            _console_tcl = os.path.join(_tk_dir, "console.tcl")
            if os.path.isfile(_console_tcl):
                with open(_console_tcl, "w") as _f:
                    _f.write(_stub_tcl)

        print("post-build: bundled Tcl/Tk libraries and script directories")
